//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace WebApplication1.Polaczenie {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Polaczenie.IWCFService")]
    public interface IWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/dodajPracownika", ReplyAction="http://tempuri.org/IWCFService/dodajPracownikaResponse")]
        void dodajPracownika(string imie, string nazwisko, string pesel, int nr_magazynu);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/dodajPracownika", ReplyAction="http://tempuri.org/IWCFService/dodajPracownikaResponse")]
        System.Threading.Tasks.Task dodajPracownikaAsync(string imie, string nazwisko, string pesel, int nr_magazynu);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/dodajTowar", ReplyAction="http://tempuri.org/IWCFService/dodajTowarResponse")]
        void dodajTowar(string nazwa_towaru, int ilosc_towaru, int cena, int nr_magazynu);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/dodajTowar", ReplyAction="http://tempuri.org/IWCFService/dodajTowarResponse")]
        System.Threading.Tasks.Task dodajTowarAsync(string nazwa_towaru, int ilosc_towaru, int cena, int nr_magazynu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/dodajMagazyn", ReplyAction="http://tempuri.org/IWCFService/dodajMagazynResponse")]
        void dodajMagazyn(string nazwa, string miasto, string adres);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/dodajMagazyn", ReplyAction="http://tempuri.org/IWCFService/dodajMagazynResponse")]
        System.Threading.Tasks.Task dodajMagazynAsync(string nazwa, string miasto, string adres);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/usunMagazyn", ReplyAction="http://tempuri.org/IWCFService/usunMagazynResponse")]
        void usunMagazyn(int id_magazynu);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/usunMagazyn", ReplyAction="http://tempuri.org/IWCFService/usunMagazynResponse")]
        System.Threading.Tasks.Task usunMagazynAsync(int id_magazynu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/usunPracownika", ReplyAction="http://tempuri.org/IWCFService/usunPracownikaResponse")]
        void usunPracownika(int id_pracownika);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/usunPracownika", ReplyAction="http://tempuri.org/IWCFService/usunPracownikaResponse")]
        System.Threading.Tasks.Task usunPracownikaAsync(int id_pracownika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/usunTowar", ReplyAction="http://tempuri.org/IWCFService/usunTowarResponse")]
        void usunTowar(int id_towaru);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/usunTowar", ReplyAction="http://tempuri.org/IWCFService/usunTowarResponse")]
        System.Threading.Tasks.Task usunTowarAsync(int id_towaru);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFServiceChannel : WebApplication1.Polaczenie.IWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFServiceClient : System.ServiceModel.ClientBase<WebApplication1.Polaczenie.IWCFService>, WebApplication1.Polaczenie.IWCFService {
        
        public WCFServiceClient() {
        }
        
        public WCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void dodajPracownika(string imie, string nazwisko, string pesel, int nr_magazynu) {
            base.Channel.dodajPracownika(imie, nazwisko, pesel, nr_magazynu);
        }
        
        public System.Threading.Tasks.Task dodajPracownikaAsync(string imie, string nazwisko, string pesel, int nr_magazynu)        {
            return base.Channel.dodajPracownikaAsync(imie, nazwisko, pesel, nr_magazynu);
        }
        
        public void dodajTowar(string nazwa_towaru, int ilosc_towaru, int cena, int nr_magazynu){
            base.Channel.dodajTowar(nazwa_towaru, ilosc_towaru, cena, nr_magazynu);
        }
        
        public System.Threading.Tasks.Task dodajTowarAsync(string nazwa_towaru, int ilosc_towaru, int cena, int nr_magazynu){
            return base.Channel.dodajTowarAsync(nazwa_towaru, ilosc_towaru, cena, nr_magazynu);
        }
        
        public void dodajMagazyn(string nazwa, string miasto, string adres) {
            base.Channel.dodajMagazyn(nazwa, miasto, adres);
        }
        
        public System.Threading.Tasks.Task dodajMagazynAsync(string nazwa, string miasto, string adres){
            return base.Channel.dodajMagazynAsync(nazwa, miasto, adres);
        }
        
        public void usunMagazyn(int id_magazynu) {
            base.Channel.usunMagazyn(id_magazynu);
        }
        
        public System.Threading.Tasks.Task usunMagazynAsync(int id_magazynu) {
            return base.Channel.usunMagazynAsync(id_magazynu);
        }
        
        public void usunPracownika(int id_pracownika) {
            base.Channel.usunPracownika(id_pracownika);
        }
        
        public System.Threading.Tasks.Task usunPracownikaAsync(int id_pracownika) {
            return base.Channel.usunPracownikaAsync(id_pracownika);
        }
        
        public void usunTowar(int id) {
            base.Channel.usunTowar(id);
        }
        
        public System.Threading.Tasks.Task usunTowarAsync(int id_towaru) {
            return base.Channel.usunTowarAsync(id_towaru);
        }

    }
}
